# Generated by Django 3.2.2 on 2021-05-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChucVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenChucVu', models.CharField(max_length=255)),
                ('baoHiem', models.CharField(max_length=255)),
                ('troCap', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ChucVu',
                'verbose_name_plural': 'ChucVu',
                'db_table': 'chucvu',
            },
        ),
        migrations.CreateModel(
            name='ChuyenMon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenChuyenMon', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ChuyenMon',
                'verbose_name_plural': 'ChuyenMon',
                'db_table': 'chuyenmon',
            },
        ),
        migrations.CreateModel(
            name='MucLuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maMucLuong', models.CharField(max_length=255)),
                ('soTien', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'MucLuong',
                'verbose_name_plural': 'MucLuong',
                'db_table': 'mucluong',
            },
        ),
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maPhongBan', models.CharField(max_length=255)),
                ('tenPhongBan', models.CharField(max_length=255)),
                ('diaChi', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'PhongBan',
                'verbose_name_plural': 'PhongBan',
                'db_table': 'phongban',
            },
        ),
        migrations.CreateModel(
            name='ThanNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoVaTen', models.CharField(max_length=255)),
                ('diaChi', models.TextField()),
                ('soDienThoai', models.BigIntegerField(blank=True, null=True)),
                ('quanHe', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ThanNhan',
                'verbose_name_plural': 'ThanNhan',
                'db_table': 'thannhan',
            },
        ),
        migrations.CreateModel(
            name='TrinhDoNgoaiNgu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaiNgonNgu', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'TrinhDoNgoaiNgu',
                'verbose_name_plural': 'TrinhDoNgoaiNgu',
                'db_table': 'trinhdoNN',
            },
        ),
    ]
