# Generated by Django 3.2.2 on 2021-05-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhenThuongKyLuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maKTKL', models.CharField(max_length=255)),
                ('tenKTKL', models.CharField(max_length=255)),
                ('hinhthucKTKL', models.PositiveSmallIntegerField(choices=[(0, 'Chuyển tiền qua thẻ'), (1, 'Chuyển tiền mặt'), (2, 'Trừ lương'), (3, 'Thu tiền phạt')], default=0)),
                ('soTienKTKL', models.BigIntegerField(blank=True, null=True)),
                ('laKT', models.BooleanField(default=True, verbose_name='Đây là Khen thưởng')),
            ],
            options={
                'verbose_name': 'KhenThuongKyLuat',
                'verbose_name_plural': 'KhenThuongKyLuat',
                'db_table': 'khenthuong_kyluat',
            },
        ),
    ]
