# Generated by Django 3.2.2 on 2021-05-10 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nhansu', '0002_khenthuongkyluat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChuyenMonNhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mucDo', models.CharField(max_length=255)),
                ('chuyenMon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhansu.chuyenmon')),
            ],
            options={
                'verbose_name': 'ChuyenMonNhanVien',
                'verbose_name_plural': 'ChuyenMonNhanVien',
                'db_table': 'chuyenmon_nhanvien',
            },
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoVaTen', models.CharField(max_length=255)),
                ('diaChi', models.TextField()),
                ('email', models.CharField(max_length=255)),
                ('ngaySinh', models.DateField(blank=True, null=True)),
                ('soDienThoai', models.BigIntegerField(blank=True, null=True)),
                ('trangThaiLamViec', models.BooleanField(default=True, verbose_name='Đang làm việc')),
                ('chuyenMon', models.ManyToManyField(related_name='chuyenMon', through='nhansu.ChuyenMonNhanVien', to='nhansu.ChuyenMon')),
                ('taikhoan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thanNhan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhansu.thannhan')),
            ],
            options={
                'verbose_name': 'NguoiDung',
                'verbose_name_plural': 'NguoiDung',
                'db_table': 'nguoidung',
            },
        ),
        migrations.CreateModel(
            name='TDNNNhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mucDo', models.CharField(max_length=255)),
                ('ngonNgu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhansu.trinhdongoaingu')),
                ('nhanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhansu.nguoidung')),
            ],
            options={
                'verbose_name': 'TDNNNhanVien',
                'verbose_name_plural': 'TDNNNhanVien',
                'db_table': 'tdnn_nhanvien',
            },
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='trinhDoNN',
            field=models.ManyToManyField(related_name='trinhDoNN', through='nhansu.TDNNNhanVien', to='nhansu.TrinhDoNgoaiNgu'),
        ),
        migrations.CreateModel(
            name='HoSoLyLich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenNoiCongTac', models.CharField(max_length=255)),
                ('thoiGian', models.CharField(max_length=255)),
                ('diaChi', models.TextField()),
                ('nhanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhansu.nguoidung')),
            ],
            options={
                'verbose_name': 'HoSoLyLich',
                'verbose_name_plural': 'HoSoLyLich',
                'db_table': 'hosolylich',
            },
        ),
        migrations.AddField(
            model_name='chuyenmonnhanvien',
            name='nhanVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhansu.nguoidung'),
        ),
    ]
