# Generated by Django 3.2.2 on 2021-05-10 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0003_auto_20210510_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosolylich',
            name='nhanVien',
        ),
        migrations.RemoveField(
            model_name='nguoidung',
            name='chuyenMon',
        ),
        migrations.RemoveField(
            model_name='nguoidung',
            name='taikhoan',
        ),
        migrations.RemoveField(
            model_name='nguoidung',
            name='thanNhan',
        ),
        migrations.RemoveField(
            model_name='nguoidung',
            name='trinhDoNN',
        ),
        migrations.RemoveField(
            model_name='tdnnnhanvien',
            name='ngonNgu',
        ),
        migrations.RemoveField(
            model_name='tdnnnhanvien',
            name='nhanVien',
        ),
        migrations.DeleteModel(
            name='ChuyenMonNhanVien',
        ),
        migrations.DeleteModel(
            name='HoSoLyLich',
        ),
        migrations.DeleteModel(
            name='NguoiDung',
        ),
        migrations.DeleteModel(
            name='TDNNNhanVien',
        ),
    ]
