# Generated by Django 3.2.2 on 2021-05-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0005_chuyenmonnhanvien_hosolylich_nguoidung_tdnnnhanvien'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='trangThaiLamViec',
            field=models.BooleanField(default=True, verbose_name='Đang làm việc'),
        ),
    ]
