# Generated by Django 3.2.2 on 2021-05-10 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0006_nguoidung_trangthailamviec'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVienPhongBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_batDau', models.DateField(blank=True, null=True, verbose_name='Thời gian bắt đầu')),
                ('tg_ketThuc', models.DateField(blank=True, null=True, verbose_name='Thời gian kết thúc')),
                ('chucVu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhansu.chucvu')),
                ('mucLuong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhansu.mucluong')),
                ('nhanVien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhansu.nguoidung')),
                ('phongBan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhansu.phongban')),
            ],
            options={
                'verbose_name': 'NhanVienPhongBan',
                'verbose_name_plural': 'NhanVienPhongBan',
                'db_table': 'nhanvien_phongban',
            },
        ),
        migrations.CreateModel(
            name='PhieuLuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayPhat', models.DateField(blank=True, null=True)),
                ('tongTien', models.BigIntegerField()),
                ('nhanVienPB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhansu.nhanvienphongban')),
            ],
            options={
                'verbose_name': 'PhieuLuong',
                'verbose_name_plural': 'PhieuLuong',
                'db_table': 'phieuluong',
            },
        ),
        migrations.CreateModel(
            name='NhanVienKTKL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoiGian', models.DateField(blank=True, null=True)),
                ('ktkl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhansu.khenthuongkyluat')),
                ('nhanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhansu.nguoidung')),
            ],
            options={
                'verbose_name': 'NhanVienKTKL',
                'verbose_name_plural': 'NhanVienKTKL',
                'db_table': 'nhanVienKTKL',
            },
        ),
    ]
