# Generated by Django 3.2.2 on 2021-05-10 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0007_nhanvienktkl_nhanvienphongban_phieuluong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhanvienktkl',
            name='nhanVien',
        ),
    ]
