# Generated by Django 3.2.2 on 2021-05-10 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0008_remove_nhanvienktkl_nhanvien'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvienktkl',
            name='nhanVienPB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhansu.nhanvienphongban'),
        ),
    ]
