# Generated by Django 3.2.2 on 2021-05-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0009_nhanvienktkl_nhanvienpb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HoSoLyLich',
        ),
    ]
