# Generated by Django 3.2.2 on 2021-05-11 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0010_delete_hosolylich'),
    ]

    operations = [
        migrations.CreateModel(
            name='LyLichCongTac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenNoiCongTac', models.CharField(max_length=255)),
                ('thoiGian', models.CharField(max_length=255)),
                ('diaChi', models.TextField()),
                ('nhanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhansu.nguoidung')),
            ],
            options={
                'verbose_name': 'HoSoLyLich',
                'verbose_name_plural': 'HoSoLyLich',
                'db_table': 'hosolylich',
            },
        ),
    ]
