# Generated by Django 3.2.2 on 2021-05-12 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0011_lylichcongtac'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lylichcongtac',
            options={'verbose_name': 'LyLichCongTac', 'verbose_name_plural': 'LyLichCongTac'},
        ),
        migrations.AlterModelTable(
            name='lylichcongtac',
            table='lyLichCongTac',
        ),
    ]
